// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbzq9Vk1OElmKwBL7IW66HLhK_y6aGD2A',
    appId: '1:499615961316:web:9ee5f0cdb6118c02c15cf1',
    messagingSenderId: '499615961316',
    projectId: 'ertegi-9270d',
    authDomain: 'ertegi-9270d.firebaseapp.com',
    storageBucket: 'ertegi-9270d.firebasestorage.app',
    measurementId: 'G-MF5RRQ5LDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaM8zl3HgFrEEh7piMyW8TwbWrzS8p5s',
    appId: '1:499615961316:android:7007a1466fa1556dc15cf1',
    messagingSenderId: '499615961316',
    projectId: 'ertegi-9270d',
    storageBucket: 'ertegi-9270d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHPGWongGwquYQUScoDiCYy9dh6eM4Cg',
    appId: '1:499615961316:ios:93844796d026c147c15cf1',
    messagingSenderId: '499615961316',
    projectId: 'ertegi-9270d',
    storageBucket: 'ertegi-9270d.firebasestorage.app',
    iosClientId: '499615961316-69ld7v4qmkt1itcjd9c9ac46qk94lv8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZHPGWongGwquYQUScoDiCYy9dh6eM4Cg',
    appId: '1:499615961316:ios:93844796d026c147c15cf1',
    messagingSenderId: '499615961316',
    projectId: 'ertegi-9270d',
    storageBucket: 'ertegi-9270d.firebasestorage.app',
    iosClientId: '499615961316-69ld7v4qmkt1itcjd9c9ac46qk94lv8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbzq9Vk1OElmKwBL7IW66HLhK_y6aGD2A',
    appId: '1:499615961316:web:3e122385a5f9d906c15cf1',
    messagingSenderId: '499615961316',
    projectId: 'ertegi-9270d',
    authDomain: 'ertegi-9270d.firebaseapp.com',
    storageBucket: 'ertegi-9270d.firebasestorage.app',
    measurementId: 'G-6N99N9KVP7',
  );

}